local uci = require "luci.model.uci".cursor()
local sys = require "luci.sys"
local util = require "luci.util"

local function generate_secret(length)
	length = length or 16
	local chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ234567"
	local secret = ""
	
	-- Try to use cryptographically secure random source first
	local f = io.open("/dev/urandom", "rb")
	if f then
		local data = f:read(length)
		f:close()
		if data then
			for i = 1, #data do
				local byte = string.byte(data, i)
				secret = secret .. chars:sub((byte % #chars) + 1, (byte % #chars) + 1)
			end
			return secret
		end
	end
	
	-- Fallback: use math.random with better seeding
	math.randomseed(os.time() + os.clock() * 1000000)
	for i = 1, length do
		local idx = math.random(1, #chars)
		secret = secret .. chars:sub(idx, idx)
	end
	return secret
end

local function escape_html(s)
	return (tostring(s or ""):gsub("&", "&amp;"):gsub("<", "&lt;"):gsub(">", "&gt;"):gsub('"', "&quot;"))
end

local function urlencode(str)
	return (str:gsub("([^%w%-%.%_%~])", function(c)
		return string.format("%%%02X", string.byte(c))
	end))
end

local function build_otp_uri(secret)
	local hostname = sys.hostname() or "OpenWrt"
	local label = urlencode(hostname) .. ":root"
	local issuer = urlencode(hostname)
	return string.format(
		"otpauth://totp/%s?secret=%s&issuer=%s",
		label, secret, issuer
	)
end

local function build_qr_html(secret)
	if not secret or #secret < 16 then
		return '<div style="color:#c00;">' ..
			translate("Secret key is not ready yet. Save settings or reload the page.") ..
			'</div>'
	end

	local otp_uri = build_otp_uri(secret)

	if sys.call("which qrencode >/dev/null 2>&1") == 0 then
		-- OpenWrt qrencode is built without PNG; SVG inline output works everywhere.
		local qr_svg = util.trim(sys.exec(string.format(
			"qrencode --inline --8bit --type=SVG --output=- %s 2>/dev/null",
			util.shellquote(otp_uri)
		)) or "")

		if qr_svg ~= "" and qr_svg:find("<svg") then
			return string.format(
				'<div style="margin:10px 0;max-width:220px;">%s</div>',
				qr_svg
			)
		end
	end

	if sys.call("which qrencode >/dev/null 2>&1") ~= 0 then
		return '<div style="color:#c00;">' ..
			translate("Error: 'qrencode' package is missing. Install: opkg install qrencode") ..
			'</div>'
	end

	return '<div style="color:#c00;">' ..
		translate("Failed to generate QR code. Check system log (logread | grep twofa).") ..
		'</div>'
end

local current_secret
local ok = pcall(function()
	current_secret = uci:get("twofa", "global", "secret")
end)

if not ok or not current_secret or #current_secret < 16 then
	current_secret = generate_secret()
	pcall(function()
		uci:set("twofa", "global", "secret", current_secret)
		uci:commit("twofa")
	end)
end

local m, s, o

m = Map("twofa", translate("Two-Factor Authentication"),
	translate("Protect your router with TOTP-based 2FA (Google Authenticator, Authy, etc.)."))

s = m:section(NamedSection, "global", "twofa", translate("Global Settings"))
s.anonymous = true
s.addremove = false

o = s:option(Flag, "enabled", translate("Enable 2FA"),
	translate("Enforce two-factor authentication for OpenWrt Web Interface."))
o.rmempty = false

o = s:option(DummyValue, "_secret_display", translate("Secret Key"))
o.rawhtml = true
function o.cfgvalue()
	return string.format(
		'<code style="font-size:16px;letter-spacing:2px;">%s</code>',
		escape_html(current_secret or "")
	)
end
o.description = translate("Enter this key manually if you cannot scan the QR code.")

o = s:option(DummyValue, "_qr_code", translate("QR Code"))
o.rawhtml = true
function o.cfgvalue()
	return build_qr_html(current_secret)
end
o.description = translate("Scan this with your authenticator app.")

o = s:option(Flag, "reset_secret", translate("Regenerate Secret"),
	translate("Check this and save to generate a new secret key. WARNING: Your old codes will stop working immediately."))
o.rmempty = true
o.default = "0"

function o.cfgvalue()
	return "0"
end

function o.write(self, section, value)
	if value == "1" then
		current_secret = generate_secret()
		uci:set("twofa", "global", "secret", current_secret)
		sys.call("logger -t twofa 'Secret key regenerated by user'")
	end
end

return m
