local sys  = require "luci.sys"
local util = require "luci.util"
local fs   = require "nixio.fs"

-- Secret lives in a root-only file rather than UCI. See the audit notes in
-- /etc/uci-defaults/10-luci-app-twofa for the threat model behind this.
local SECRET_FILE = "/etc/twofa.secret"

local function read_secret()
	-- The LuCI dispatcher runs as root, so a direct read is fine and we
	-- skip the ubus/file-ACL ceremony entirely.
	local f = io.open(SECRET_FILE, "rb")
	if not f then return nil end
	local data = f:read("*l") or ""
	f:close()
	data = data:gsub("%s+", "")
	if #data >= 16 then return data end
	return nil
end

local function regenerate_secret()
	-- Delegate to twofa-genkey: it owns the umask/chmod/atomic-rename dance
	-- so the secret file is never world-readable, not even for a microsecond.
	local s = util.trim(sys.exec("/usr/sbin/twofa-genkey 2>/dev/null") or "")
	if s:match("^[A-Z2-7]+$") and #s == 16 then
		sys.call("logger -t twofa 'Secret key regenerated by user'")
		return s
	end
	sys.call("logger -t twofa 'Secret regeneration FAILED: twofa-genkey returned no usable output'")
	return nil
end

local function escape_html(s)
	return (tostring(s or "")
		:gsub("&", "&amp;"):gsub("<", "&lt;")
		:gsub(">", "&gt;"):gsub('"', "&quot;"))
end

local function urlencode(str)
	return (str:gsub("([^%w%-%.%_%~])", function(c)
		return string.format("%%%02X", string.byte(c))
	end))
end

local function build_otp_uri(secret)
	local hostname = sys.hostname() or "OpenWrt"
	local label  = urlencode(hostname) .. ":root"
	local issuer = urlencode(hostname)
	return string.format(
		"otpauth://totp/%s?secret=%s&issuer=%s",
		label, secret, issuer
	)
end

local function build_qr_html(secret)
	if not secret or #secret < 16 then
		return '<div style="color:#c00;">' ..
			translate("Secret key is not configured yet. Tick 'Regenerate' below and save to create one.") ..
			'</div>'
	end

	local otp_uri = build_otp_uri(secret)

	if sys.call("which qrencode >/dev/null 2>&1") == 0 then
		local qr_svg = util.trim(sys.exec(string.format(
			"qrencode --inline --8bit --type=SVG --output=- %s 2>/dev/null",
			util.shellquote(otp_uri)
		)) or "")

		if qr_svg ~= "" and qr_svg:find("<svg") then
			return string.format(
				'<div style="margin:10px 0;max-width:220px;">%s</div>',
				qr_svg
			)
		end
	end

	if sys.call("which qrencode >/dev/null 2>&1") ~= 0 then
		return '<div style="color:#c00;">' ..
			translate("Error: 'qrencode' package is missing. Install: opkg install qrencode") ..
			'</div>'
	end

	return '<div style="color:#c00;">' ..
		translate("Failed to generate QR code. Check system log (logread | grep twofa).") ..
		'</div>'
end

-- Read current secret. DO NOT auto-generate at render time: that races
-- between concurrent requests, can silently invalidate the user's existing
-- authenticator binding, and (in the old code path) could fall back to a
-- weak math.random secret if /dev/urandom was unreadable. The secret must
-- be created exactly once by uci-defaults (on install) or explicitly by
-- the user via the Regenerate button.
local current_secret = read_secret()

local m, s, o

m = Map("twofa", translate("Two-Factor Authentication"),
	translate("Protect your router with TOTP-based 2FA (Google Authenticator, Authy, etc.)."))

s = m:section(NamedSection, "global", "twofa", translate("Global Settings"))
s.anonymous = true
s.addremove = false

o = s:option(Flag, "enabled", translate("Enable 2FA"),
	translate("Enforce two-factor authentication for OpenWrt Web Interface."))
o.rmempty = false

o = s:option(DummyValue, "_secret_display", translate("Secret Key"))
o.rawhtml = true
function o.cfgvalue()
	if not current_secret then
		return '<code style="color:#c00;">' ..
			translate("(not configured - press Regenerate)") .. '</code>'
	end
	return string.format(
		'<code style="font-size:16px;letter-spacing:2px;">%s</code>',
		escape_html(current_secret)
	)
end
o.description = translate("Stored in /etc/twofa.secret (mode 0600). Enter this manually if you cannot scan the QR code.")

o = s:option(DummyValue, "_qr_code", translate("QR Code"))
o.rawhtml = true
function o.cfgvalue()
	return build_qr_html(current_secret)
end
o.description = translate("Scan this with your authenticator app.")

o = s:option(Flag, "_regenerate", translate("Regenerate Secret"),
	translate("Tick and save to generate a brand-new secret. WARNING: every existing authenticator binding stops working immediately, and every active session is forced to re-verify."))
o.rmempty = true
o.default = "0"

function o.cfgvalue()
	-- Always render unchecked; we never persist this as a UCI option.
	return "0"
end

function o.write(self, section, value)
	if value == "1" then
		local fresh = regenerate_secret()
		if fresh then
			current_secret = fresh
			-- Drop session state so every active session must re-prove
			-- 2FA against the new secret. The rpcd plugin tolerates a
			-- missing state file (treats it as empty).
			fs.unlink("/var/run/luci-twofa-sessions.json")
		end
	end
end

return m
