include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-twofa
PKG_VERSION:=1.0
PKG_RELEASE:=15

PKG_LICENSE:=MIT
PKG_MAINTAINER:=YourName

LUCI_TITLE:=Two-factor authentication for LuCI
LUCI_DEPENDS:=+qrencode +luci-lib-nixio +luci-base +luci-compat
LUCI_PKGARCH:=all

# i18n packaging model (matches every other LuCI app):
#
#   luci-app-twofa            - English-only, no translation files at all.
#   luci-i18n-twofa-zh-cn     - auto-generated by luci.mk, depends on the main
#                               package, ships luci-app-twofa.zh-cn.lmo.
#
# po/zh_Hans/ is the language source directory; luci.mk's built-in
# LUCI_LC_ALIAS.zh_Hans=zh-cn maps it to the canonical `zh-cn.lmo` filename
# and the canonical `luci-i18n-<base>-zh-cn` package name. Users get Chinese
# by installing the language pack:
#
#   opkg install luci-i18n-twofa-zh-cn

include $(TOPDIR)/feeds/luci/luci.mk

# ---------------------------------------------------------------------------
# Main package: runtime setup only. No translation logic lives here.
# ---------------------------------------------------------------------------
define Package/$(PKG_NAME)/postinst
#!/bin/sh
[ -n "$${IPKG_INSTROOT}" ] && exit 0

# rpcd: restart so /usr/libexec/rpcd/luci-app-twofa is enumerated and the
# luci-app-twofa ubus object becomes resolvable (rpcd derives the object name
# from the script's basename verbatim).
/etc/init.d/rpcd enable >/dev/null 2>&1 || true
/etc/init.d/rpcd restart >/dev/null 2>&1 || true

# Drop any stale session-state from a previous install so old ACL snapshots
# don't get re-applied to brand-new sessions.
rm -f /var/run/luci-twofa-sessions.json

# Clear LuCI menu/module cache so new menu.d/acl.d entries take effect.
rm -rf /tmp/luci-indexcache /tmp/luci-modulecache 2>/dev/null

exit 0
endef

define Package/$(PKG_NAME)/postrm
#!/bin/sh
rm -f /var/run/luci-twofa-sessions.json 2>/dev/null
/etc/init.d/rpcd restart >/dev/null 2>&1 || true
rm -rf /tmp/luci-indexcache /tmp/luci-modulecache 2>/dev/null
exit 0
endef

# ---------------------------------------------------------------------------
# Language pack override: ImmortalWrt's UCI default `luci.main.lang=zh_Hans`
# is normalised by LuCI's i18n loader (gsub('_','-'):lower()) into `zh-hans`
# before opening `<app>.<lang>.lmo`. The auto-generated package only ships
# `luci-app-twofa.zh-cn.lmo`, which never matches `zh-hans`, so we drop a
# sibling alias from the language pack's own postinst. Doing it here (and
# NOT in the main package) means the alias only exists when Chinese is
# actually installed, which is what the user expects.
#
# These definitions come AFTER include luci.mk on purpose - Make's lazy
# evaluation lets them override the empty postinst that BuildLuciPackages
# generates by default.
# ---------------------------------------------------------------------------
define Package/luci-i18n-twofa-zh-cn/postinst
#!/bin/sh
[ -n "$${IPKG_INSTROOT}" ] && exit 0
src=/usr/lib/lua/luci/i18n/luci-app-twofa.zh-cn.lmo
dst=/usr/lib/lua/luci/i18n/luci-app-twofa.zh-hans.lmo
if [ -f "$$src" ] && [ ! -e "$$dst" ]; then
	cp -f "$$src" "$$dst"
fi
rm -rf /tmp/luci-indexcache /tmp/luci-modulecache 2>/dev/null
exit 0
endef

define Package/luci-i18n-twofa-zh-cn/postrm
#!/bin/sh
rm -f /usr/lib/lua/luci/i18n/luci-app-twofa.zh-hans.lmo 2>/dev/null
rm -rf /tmp/luci-indexcache /tmp/luci-modulecache 2>/dev/null
exit 0
endef

# call BuildPackage - OpenWrt buildroot signature
