include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-twofa
PKG_VERSION:=1.0
PKG_RELEASE:=16

# luci.mk auto-generates luci-i18n-<name>-<lang> packages whose VERSION is
# pulled from PKG_PO_VERSION (default: $(call findrev) on po/ via git log).
# Our CI copies the source into the SDK without a .git dir, so findrev
# returns empty and i18n ipks come out as `luci-i18n-twofa-zh-cn_0_<arch>.ipk`.
# Tie PKG_PO_VERSION to the main package's version so all four ipks of a
# release share `1.0-r15` (or whatever PKG_VERSION-rPKG_RELEASE evaluates to).
# Must be assigned BEFORE include luci.mk - luci.mk uses ?= so it loses to
# any prior assignment.
PKG_PO_VERSION:=$(PKG_VERSION)-r$(PKG_RELEASE)

PKG_LICENSE:=MIT
PKG_MAINTAINER:=YourName

LUCI_TITLE:=Two-factor authentication for LuCI
LUCI_DEPENDS:=+qrencode +luci-lib-nixio +luci-base +luci-compat
LUCI_PKGARCH:=all

# i18n packaging model (matches every other LuCI app):
#
#   luci-app-twofa            - English-only, no translation files at all.
#   luci-i18n-twofa-zh-cn     - auto-generated by luci.mk, depends on the main
#                               package, ships luci-app-twofa.zh-cn.lmo.
#
# po/zh_Hans/ is the language source directory; luci.mk's built-in
# LUCI_LC_ALIAS.zh_Hans=zh-cn maps it to the canonical `zh-cn.lmo` filename
# and the canonical `luci-i18n-<base>-zh-cn` package name. Users get Chinese
# by installing the language pack:
#
#   opkg install luci-i18n-twofa-zh-cn

include $(TOPDIR)/feeds/luci/luci.mk

# ---------------------------------------------------------------------------
# Main package: runtime setup only. No translation logic lives here.
# ---------------------------------------------------------------------------
define Package/$(PKG_NAME)/postinst
#!/bin/sh
[ -n "$${IPKG_INSTROOT}" ] && exit 0

# Ensure binaries we ship are executable. opkg should preserve modes but
# IPK roundtrips on some hosts have been known to strip the +x bit.
chmod +x /usr/libexec/rpcd/luci-app-twofa     2>/dev/null || true
chmod +x /usr/sbin/twofa-genkey               2>/dev/null || true
chmod +x /usr/sbin/luci-app-twofa-guardd      2>/dev/null || true
chmod +x /etc/init.d/luci-app-twofa-guard     2>/dev/null || true

# rpcd: restart so /usr/libexec/rpcd/luci-app-twofa is enumerated and the
# luci-app-twofa ubus object becomes resolvable (rpcd derives the object name
# from the script's basename verbatim).
/etc/init.d/rpcd enable >/dev/null 2>&1 || true
/etc/init.d/rpcd restart >/dev/null 2>&1 || true

# Drop any stale session-state from a previous install so old ACL snapshots
# don't get re-applied to brand-new sessions.
rm -f /var/run/luci-twofa-sessions.json

# session-guard daemon: this is what actually closes the non-browser bypass
# (see /usr/sbin/luci-app-twofa-guardd for the threat model). Enabling and
# starting here means a fresh install is protected immediately; the
# uci-defaults script does the same on factory reset.
/etc/init.d/luci-app-twofa-guard enable  >/dev/null 2>&1 || true
/etc/init.d/luci-app-twofa-guard restart >/dev/null 2>&1 || true

# Clear LuCI menu/module cache so new menu.d/acl.d entries take effect.
rm -rf /tmp/luci-indexcache /tmp/luci-modulecache 2>/dev/null

exit 0
endef

define Package/$(PKG_NAME)/prerm
#!/bin/sh
[ -n "$${IPKG_INSTROOT}" ] && exit 0
/etc/init.d/luci-app-twofa-guard stop    >/dev/null 2>&1 || true
/etc/init.d/luci-app-twofa-guard disable >/dev/null 2>&1 || true
exit 0
endef

define Package/$(PKG_NAME)/postrm
#!/bin/sh
rm -f /var/run/luci-twofa-sessions.json 2>/dev/null
# NOTE: we intentionally do NOT delete /etc/twofa.secret on uninstall.
# The user may want to reinstall without losing their authenticator binding;
# they can `rm /etc/twofa.secret` manually if they want a hard wipe.
/etc/init.d/rpcd restart >/dev/null 2>&1 || true
rm -rf /tmp/luci-indexcache /tmp/luci-modulecache 2>/dev/null
exit 0
endef

# ---------------------------------------------------------------------------
# Language pack override: ImmortalWrt's UCI default `luci.main.lang=zh_Hans`
# is normalised by LuCI's i18n loader (gsub('_','-'):lower()) into `zh-hans`
# before opening `<app>.<lang>.lmo`. The auto-generated package only ships
# `luci-app-twofa.zh-cn.lmo`, which never matches `zh-hans`, so we drop a
# sibling alias from the language pack's own postinst. Doing it here (and
# NOT in the main package) means the alias only exists when Chinese is
# actually installed, which is what the user expects.
#
# These definitions come AFTER include luci.mk on purpose - Make's lazy
# evaluation lets them override the empty postinst that BuildLuciPackages
# generates by default.
# ---------------------------------------------------------------------------
define Package/luci-i18n-twofa-zh-cn/postinst
#!/bin/sh
[ -n "$${IPKG_INSTROOT}" ] && exit 0
src=/usr/lib/lua/luci/i18n/luci-app-twofa.zh-cn.lmo
dst=/usr/lib/lua/luci/i18n/luci-app-twofa.zh-hans.lmo
if [ -f "$$src" ] && [ ! -e "$$dst" ]; then
	cp -f "$$src" "$$dst"
fi
rm -rf /tmp/luci-indexcache /tmp/luci-modulecache 2>/dev/null
exit 0
endef

define Package/luci-i18n-twofa-zh-cn/postrm
#!/bin/sh
rm -f /usr/lib/lua/luci/i18n/luci-app-twofa.zh-hans.lmo 2>/dev/null
rm -rf /tmp/luci-indexcache /tmp/luci-modulecache 2>/dev/null
exit 0
endef

# call BuildPackage - OpenWrt buildroot signature
